### ISSUE TITLE
RuntimeError: The expanded size of the tensor (25) must match the existing size (73)

### ISSUE THREAD

**Issue by djinnome** [ifding/graph-neural-networks#2]
Hi folks,

 I got the following error when attempting to run [MPNN on Google Colab](https://drive.google.com/open?id=1uJ-Z9Y2ncjLRQQVKKfU-pxVXMcwrOv6i)

```bash
$ cd graph-neural-networks && \
python download_data.py qm9 -p mpnn-data/ && \
python main.py --datasetPath mpnn-data/qm9/dsgdb9nsd/ 


Traceback (most recent call last):
  File "main.py", line 328, in <module>
    main(args)
  File "main.py", line 190, in main
    train(train_loader, model, criterion, optimizer, epoch, evaluation, logger)
  File "main.py", line 249, in train
    output = model(g, h, e)
  File "/content/.pyenv/versions/miniconda-latest/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/graph-neural-networks/models/MPNN.py", line 74, in forward
    m = self.m[0].forward(h[t], h_aux, e_aux)
  File "/content/graph-neural-networks/models/MessageFunction.py", line 39, in forward
    return self.m_function(h_v, h_w, e_vw, args)
  File "/content/graph-neural-networks/models/MessageFunction.py", line 126, in m_mpnn
    h_w_rows = h_w[..., None].expand(h_w.size(0), h_w.size(1), h_v.size(1)).contiguous()
  File "/content/.pyenv/versions/miniconda-latest/lib/python2.7/site-packages/torch/autograd/variable.py", line 652, in expand
    return Expand(sizes)(self)
  File "/content/.pyenv/versions/miniconda-latest/lib/python2.7/site-packages/torch/autograd/_functions/tensor.py", line 115, in forward
    result = i.expand(*self.sizes)
RuntimeError: The expanded size of the tensor (25) must match the existing size (73) at               non-singleton dimension 2. at /py/conda-bld/pytorch_1493676237139/work/torch/lib/TH/THStorage.c:99
```

**Comment by djinnome** [comment]
Additional note.  running the above with `--model MPNNv2` seems to work fine.

 Will also try with `--model MPNNv3`

**Comment by djinnome** [comment]
Hmm... when attempting to run MPNNv3, I get the following error:

```bash
$ python main.py --datasetPath mpnn-data/qm9/dsgdb9nsd/ --model MPNNv3

Namespace(batch_size=100, dataset='qm9', datasetPath='mpnn-data/qm9/dsgdb9nsd/', epochs=50, logPath='./log/qm9/mpnn/', log_interval=20, lr=0.001, lr_decay=0.6, model='MPNNv3', momentum=0.9, no_cuda=False, plotLr=False, plotPath='./plot/qm9/mpnn/', prefetch=2, resume='./checkpoint/qm9/mpnn/', schedule=[0.1, 0.9])
Prepare files
Define model
	Statistics
	Create model
Optimizer
Logger
=> no best model found at './checkpoint/qm9/mpnn/model_best.pth'
Check cuda
	* Cuda
mkl-random 1.0.1 requires cython, which is not installed.
mkl-fft 1.0.0 requires cython, which is not installed.
Traceback (most recent call last):
  File "main.py", line 328, in <module>
    main(args)
  File "main.py", line 190, in main
    train(train_loader, model, criterion, optimizer, epoch, evaluation, logger)
  File "main.py", line 249, in train
    output = model(g, h, e)
  File "/content/.pyenv/versions/miniconda-latest/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/graph-neural-networks/models/MPNNv3.py", line 92, in forward
    aux = self.u[t].forward(torch.index_select(h[t], 0, ind)[:, v, :], torch.index_select(m, 0, ind), opt)
  File "/content/graph-neural-networks/models/UpdateFunction.py", line 44, in forward
    return self.u_function(h_v, m_v, opt)
  File "/content/graph-neural-networks/models/UpdateFunction.py", line 86, in u_duvenaud
    aux = torch.bmm(parameter_mat, torch.transpose(m_v.unsqueeze(-2), 1, 2))
  File "/content/.pyenv/versions/miniconda-latest/lib/python2.7/site-packages/torch/autograd/variable.py", line 532, in bmm
    return self._static_blas(Baddbmm, (output, 0, 1, self, batch), False)
  File "/content/.pyenv/versions/miniconda-latest/lib/python2.7/site-packages/torch/autograd/variable.py", line 520, in _static_blas
    return cls(alpha, beta, inplace)(*(args[:1] + args[-2:]))
  File "/content/.pyenv/versions/miniconda-latest/lib/python2.7/site-packages/torch/autograd/_functions/blas.py", line 93, in forward
    batch1, batch2, out=output)
RuntimeError: expected 3D tensor at /py/conda-bld/pytorch_1493676237139/work/torch/lib/THC/generic/THCTensorMathBlas.cu:439
```

**Comment by djinnome** [comment]
Ahh, nevermind. I installed cython and now it seems to be working

**Comment by ifding** [comment]
Great, just a reminder. It only implements some functionalities of the original papers.
